/* tn.h - token type
* programmer - ¿Ã»ø¡¯, ¿Ø»øπŒ, ¡∂πŒ»Ò
* date - 20/04/2021
*/
enum tokentypes { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TADD, TSUB, TDIV,TMUL, TLEFT, TASSIGN, TEQUAL, TNOTEQU, TLESSE, TLESSTHAN, TGREATE, TGREATTHAN, TNOT, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TOPEN, TCLOSE, TCOMMA, TMIDOPEN, TMIDCLOSE, TBIGOPEN, TBIGCLOSE, TSEMICOLON, TIDENT, TNUMBER, TFLOAT, TCMNT, TEOLCMNT, TDEFAULT,TNEWLINE, TLONGIDENT};
